### ISSUE TITLE
Фидбек

### ISSUE THREAD

**Issue by vkats-spbu** [Egor-Shast-rezka/HomeAssignmets#1]
1. Сначала замечу, что удаление репозитория и пересоздание является проявлением серьезного неуважения к труду проверяющего, т.к. вместе с репозиторием Вы стерли все замечания, которые были Вам сделаны. А значит работу прийдется перепроверять с нуля.
2. На втором занятии было сказано _переименовать_ репозитрий и _создать_ в нем структуру директорий под задачи, а не заводить новый.
3. Более того, структура репозитория Вами не выдержана
4. Вы не добавили в файлы *.cpp и *.h обязательный комментарий, о котором также говорилось на занятии
5. Для чего Вам файл [test_data.txt](https://github.com/Egor-Shast-rezka/HomeAssignmets/blob/master/test_data.txt)?

**Comment by Egor-Shast-rezka** [comment]
Добрый день. Я хочу извиниться за предоставленные мной неудобства. В мои намерения не входило проявлять неуважение к кому-либо. Удаление репозитория является следствием того, что я запутался в создании единообразия в изначальном репозитории. Впредь постараюсь не делать подобного. Также были исправлены существующие ошибки в дз.
Вот ссылка на старый репозиторий (видимо, его сохранил проверяющий):  https://github.com/DmitriyShcheka/Hello-World.git
Ссылка на новый, доработанный:  https://github.com/Egor-Shast-rezka/HomeAssignmets.git
 
Файл test_data.txt (уже удалённый), существовал из-за того, что в презентации на первой лекции в требованиях к репозиторию была строчка про тестовые данные (реализованные в первой версии кода).
 
--
Егор Шастин Олегович, b-81
Отправлено из Почты  Mail
